export const BannerCarousel = () => import('../..\\components\\template7\\_carouselBanner\\banner-carousel.vue' /* webpackChunkName: "components/banner-carousel" */).then(c => wrapFunctional(c.default || c))
export const Ko7KoCarousel = () => import('../..\\components\\template7\\_carouselBanner\\Ko7-ko-carousel.vue' /* webpackChunkName: "components/ko7-ko-carousel" */).then(c => wrapFunctional(c.default || c))
export const KoProductDetail1 = () => import('../..\\components\\template5\\Ko-ProductDetail-1.vue' /* webpackChunkName: "components/ko-product-detail1" */).then(c => wrapFunctional(c.default || c))
export const KoProductDetailHoko1 = () => import('../..\\components\\template5\\Ko-ProductDetailHoko-1.vue' /* webpackChunkName: "components/ko-product-detail-hoko1" */).then(c => wrapFunctional(c.default || c))
export const KoProductFavoritosHoko = () => import('../..\\components\\template5\\Ko-ProductFavoritosHoko.vue' /* webpackChunkName: "components/ko-product-favoritos-hoko" */).then(c => wrapFunctional(c.default || c))
export const Ko5Banner = () => import('../..\\components\\template5\\Ko5-Banner.vue' /* webpackChunkName: "components/ko5-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko5BannerFooter = () => import('../..\\components\\template5\\Ko5-BannerFooter.vue' /* webpackChunkName: "components/ko5-banner-footer" */).then(c => wrapFunctional(c.default || c))
export const Ko5Component360 = () => import('../..\\components\\template5\\Ko5-Component360.vue' /* webpackChunkName: "components/ko5-component360" */).then(c => wrapFunctional(c.default || c))
export const Ko5Contact = () => import('../..\\components\\template5\\Ko5-Contact.vue' /* webpackChunkName: "components/ko5-contact" */).then(c => wrapFunctional(c.default || c))
export const Ko5Newsletter = () => import('../..\\components\\template5\\Ko5-Newsletter.vue' /* webpackChunkName: "components/ko5-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko5ProductFavoritos = () => import('../..\\components\\template5\\Ko5-ProductFavoritos.vue' /* webpackChunkName: "components/ko5-product-favoritos" */).then(c => wrapFunctional(c.default || c))
export const Ko5ProductList = () => import('../..\\components\\template5\\Ko5-ProductList.vue' /* webpackChunkName: "components/ko5-product-list" */).then(c => wrapFunctional(c.default || c))
export const Ko5ProductListHome = () => import('../..\\components\\template5\\Ko5-ProductListHome.vue' /* webpackChunkName: "components/ko5-product-list-home" */).then(c => wrapFunctional(c.default || c))
export const Ko5ProductListHomeHoko = () => import('../..\\components\\template5\\Ko5-ProductListHomeHoko.vue' /* webpackChunkName: "components/ko5-product-list-home-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductcardKoProductCard1 = () => import('../..\\components\\template5\\_productcard\\Ko-ProductCard-1.vue' /* webpackChunkName: "components/productcard-ko-product-card1" */).then(c => wrapFunctional(c.default || c))
export const ProductcardKoProductCardHoko1 = () => import('../..\\components\\template5\\_productcard\\Ko-ProductCardHoko-1.vue' /* webpackChunkName: "components/productcard-ko-product-card-hoko1" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsCommentsProduct = () => import('../..\\components\\template5\\_productdetails\\commentsProduct.vue' /* webpackChunkName: "components/productdetails-comments-product" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsDescriptionProductHoko = () => import('../..\\components\\template5\\_productdetails\\descriptionProduct-hoko.vue' /* webpackChunkName: "components/productdetails-description-product-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsDescriptionProduct = () => import('../..\\components\\template5\\_productdetails\\descriptionProduct.vue' /* webpackChunkName: "components/productdetails-description-product" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsProductSlide = () => import('../..\\components\\template5\\_productdetails\\productSlide.vue' /* webpackChunkName: "components/productdetails-product-slide" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsProductSlideHoko = () => import('../..\\components\\template5\\_productdetails\\productSlideHoko.vue' /* webpackChunkName: "components/productdetails-product-slide-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsSelectGroup = () => import('../..\\components\\template5\\_productdetails\\selectGroup.vue' /* webpackChunkName: "components/productdetails-select-group" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsSuggestionsProducto = () => import('../..\\components\\template5\\_productdetails\\suggestionsProducto.vue' /* webpackChunkName: "components/productdetails-suggestions-producto" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsZoomImg = () => import('../..\\components\\template5\\_productdetails\\zoomImg.vue' /* webpackChunkName: "components/productdetails-zoom-img" */).then(c => wrapFunctional(c.default || c))
export const ProductofavoritoProductSlide = () => import('../..\\components\\template5\\_productofavorito\\productSlide.vue' /* webpackChunkName: "components/productofavorito-product-slide" */).then(c => wrapFunctional(c.default || c))
export const ProductofavoritoProductSlideHoko = () => import('../..\\components\\template5\\_productofavorito\\productSlideHoko.vue' /* webpackChunkName: "components/productofavorito-product-slide-hoko" */).then(c => wrapFunctional(c.default || c))
export const KoCategory1 = () => import('../..\\components\\template7\\Ko-Category-1.vue' /* webpackChunkName: "components/ko-category1" */).then(c => wrapFunctional(c.default || c))
export const KoContact = () => import('../..\\components\\template7\\Ko-Contact.vue' /* webpackChunkName: "components/ko-contact" */).then(c => wrapFunctional(c.default || c))
export const KoProductDetail = () => import('../..\\components\\template7\\Ko-ProductDetail.vue' /* webpackChunkName: "components/ko-product-detail" */).then(c => wrapFunctional(c.default || c))
export const KoProductListFilter = () => import('../..\\components\\template7\\Ko-ProductListFilter.vue' /* webpackChunkName: "components/ko-product-list-filter" */).then(c => wrapFunctional(c.default || c))
export const KoProductListSearchUp = () => import('../..\\components\\template7\\Ko-ProductListSearchUp.vue' /* webpackChunkName: "components/ko-product-list-search-up" */).then(c => wrapFunctional(c.default || c))
export const KoSocialNetworks = () => import('../..\\components\\template7\\Ko-Social-Networks.vue' /* webpackChunkName: "components/ko-social-networks" */).then(c => wrapFunctional(c.default || c))
export const Ko7Advertising = () => import('../..\\components\\template7\\Ko7-advertising.vue' /* webpackChunkName: "components/ko7-advertising" */).then(c => wrapFunctional(c.default || c))
export const Ko7BannerPromo = () => import('../..\\components\\template7\\Ko7-Banner-Promo.vue' /* webpackChunkName: "components/ko7-banner-promo" */).then(c => wrapFunctional(c.default || c))
export const Ko7Blog = () => import('../..\\components\\template7\\Ko7-blog.vue' /* webpackChunkName: "components/ko7-blog" */).then(c => wrapFunctional(c.default || c))
export const Ko7Gify = () => import('../..\\components\\template7\\Ko7-gify.vue' /* webpackChunkName: "components/ko7-gify" */).then(c => wrapFunctional(c.default || c))
export const Ko7HowWeWork = () => import('../..\\components\\template7\\Ko7-howWeWork.vue' /* webpackChunkName: "components/ko7-how-we-work" */).then(c => wrapFunctional(c.default || c))
export const Ko7Newsletter = () => import('../..\\components\\template7\\Ko7-Newsletter.vue' /* webpackChunkName: "components/ko7-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko7ProductList = () => import('../..\\components\\template7\\Ko7-ProductList.vue' /* webpackChunkName: "components/ko7-product-list" */).then(c => wrapFunctional(c.default || c))
export const Ko7Wrapper = () => import('../..\\components\\template7\\Ko7-wrapper.vue' /* webpackChunkName: "components/ko7-wrapper" */).then(c => wrapFunctional(c.default || c))
export const BlogPageKoArticulo = () => import('../..\\components\\template7\\blog_page\\Ko-articulo.vue' /* webpackChunkName: "components/blog-page-ko-articulo" */).then(c => wrapFunctional(c.default || c))
export const BlogPageKoBlog = () => import('../..\\components\\template7\\blog_page\\Ko-Blog.vue' /* webpackChunkName: "components/blog-page-ko-blog" */).then(c => wrapFunctional(c.default || c))
export const BlogBlogcard = () => import('../..\\components\\template7\\_blog\\blogcard.vue' /* webpackChunkName: "components/blog-blogcard" */).then(c => wrapFunctional(c.default || c))
export const ProductcardProductCard = () => import('../..\\components\\template7\\_productcard\\ProductCard.vue' /* webpackChunkName: "components/productcard-product-card" */).then(c => wrapFunctional(c.default || c))
export const ProductcardProductCardFilterList = () => import('../..\\components\\template7\\_productcard\\ProductCardFilterList.vue' /* webpackChunkName: "components/productcard-product-card-filter-list" */).then(c => wrapFunctional(c.default || c))
export const PromoBanner = () => import('../..\\components\\template7\\_promoBanner\\promoBanner.vue' /* webpackChunkName: "components/promo-banner" */).then(c => wrapFunctional(c.default || c))
export const BlogPageBlogcardKoCardblog = () => import('../..\\components\\template7\\blog_page\\_blogcard\\Ko-cardblog.vue' /* webpackChunkName: "components/blog-page-blogcard-ko-cardblog" */).then(c => wrapFunctional(c.default || c))
export const KoProductDetailHoko = () => import('../..\\components\\template9\\Ko-ProductDetailHoko.vue' /* webpackChunkName: "components/ko-product-detail-hoko" */).then(c => wrapFunctional(c.default || c))
export const KoProductListFilterHoko = () => import('../..\\components\\template9\\Ko-ProductListFilterHoko.vue' /* webpackChunkName: "components/ko-product-list-filter-hoko" */).then(c => wrapFunctional(c.default || c))
export const KoProductListHoko = () => import('../..\\components\\template9\\Ko-ProductListHoko.vue' /* webpackChunkName: "components/ko-product-list-hoko" */).then(c => wrapFunctional(c.default || c))
export const Ko9Banner = () => import('../..\\components\\template9\\Ko9-Banner.vue' /* webpackChunkName: "components/ko9-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko9Blog = () => import('../..\\components\\template9\\Ko9-blog.vue' /* webpackChunkName: "components/ko9-blog" */).then(c => wrapFunctional(c.default || c))
export const Ko9Newsletter = () => import('../..\\components\\template9\\Ko9-Newsletter.vue' /* webpackChunkName: "components/ko9-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko9Offers = () => import('../..\\components\\template9\\Ko9-offers.vue' /* webpackChunkName: "components/ko9-offers" */).then(c => wrapFunctional(c.default || c))
export const Ko9ProductList = () => import('../..\\components\\template9\\Ko9-ProductList.vue' /* webpackChunkName: "components/ko9-product-list" */).then(c => wrapFunctional(c.default || c))
export const Ko9SliderHoko = () => import('../..\\components\\template9\\Ko9-sliderHoko.vue' /* webpackChunkName: "components/ko9-slider-hoko" */).then(c => wrapFunctional(c.default || c))
export const Ko9Wrapper = () => import('../..\\components\\template9\\Ko9-wrapper.vue' /* webpackChunkName: "components/ko9-wrapper" */).then(c => wrapFunctional(c.default || c))
export const ProductcardProductCardHoko = () => import('../..\\components\\template9\\_productcard\\ProductCardHoko.vue' /* webpackChunkName: "components/productcard-product-card-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsOptAcordionHoko = () => import('../..\\components\\template9\\_productdetails\\OptAcordion-hoko.vue' /* webpackChunkName: "components/productdetails-opt-acordion-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsOptAcordion = () => import('../..\\components\\template9\\_productdetails\\OptAcordion.vue' /* webpackChunkName: "components/productdetails-opt-acordion" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsOptTabHoko = () => import('../..\\components\\template9\\_productdetails\\OptTab-hoko.vue' /* webpackChunkName: "components/productdetails-opt-tab-hoko" */).then(c => wrapFunctional(c.default || c))
export const ProductdetailsOptTab = () => import('../..\\components\\template9\\_productdetails\\OptTab.vue' /* webpackChunkName: "components/productdetails-opt-tab" */).then(c => wrapFunctional(c.default || c))
export const ProductofavoritoProductSlidehoko = () => import('../..\\components\\template9\\_productofavorito\\productSlidehoko.vue' /* webpackChunkName: "components/productofavorito-product-slidehoko" */).then(c => wrapFunctional(c.default || c))
export const KoNewsletter = () => import('../..\\components\\template10\\Ko-Newsletter.vue' /* webpackChunkName: "components/ko-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko10Blog = () => import('../..\\components\\template10\\Ko10-blog.vue' /* webpackChunkName: "components/ko10-blog" */).then(c => wrapFunctional(c.default || c))
export const Ko10ButtonCar = () => import('../..\\components\\template10\\Ko10-buttonCar.vue' /* webpackChunkName: "components/ko10-button-car" */).then(c => wrapFunctional(c.default || c))
export const Ko10Carousel = () => import('../..\\components\\template10\\Ko10-carousel.vue' /* webpackChunkName: "components/ko10-carousel" */).then(c => wrapFunctional(c.default || c))
export const Ko10Deals = () => import('../..\\components\\template10\\Ko10-deals.vue' /* webpackChunkName: "components/ko10-deals" */).then(c => wrapFunctional(c.default || c))
export const Ko10FeaturedProducts = () => import('../..\\components\\template10\\Ko10-featuredProducts.vue' /* webpackChunkName: "components/ko10-featured-products" */).then(c => wrapFunctional(c.default || c))
export const Ko10Section = () => import('../..\\components\\template10\\Ko10-section.vue' /* webpackChunkName: "components/ko10-section" */).then(c => wrapFunctional(c.default || c))
export const Ko10Trending = () => import('../..\\components\\template10\\Ko10-trending.vue' /* webpackChunkName: "components/ko10-trending" */).then(c => wrapFunctional(c.default || c))
export const BlogPageBlogcardKoBlogcard = () => import('../..\\components\\template10\\blog_page\\_blogcard\\ko-blogcard.vue' /* webpackChunkName: "components/blog-page-blogcard-ko-blogcard" */).then(c => wrapFunctional(c.default || c))
export const KoSocialnet = () => import('../..\\components\\template11\\ko-socialnet.vue' /* webpackChunkName: "components/ko-socialnet" */).then(c => wrapFunctional(c.default || c))
export const Ko11Blog = () => import('../..\\components\\template11\\Ko11-blog.vue' /* webpackChunkName: "components/ko11-blog" */).then(c => wrapFunctional(c.default || c))
export const Ko11Carousel = () => import('../..\\components\\template11\\Ko11-carousel.vue' /* webpackChunkName: "components/ko11-carousel" */).then(c => wrapFunctional(c.default || c))
export const Ko11Information = () => import('../..\\components\\template11\\Ko11-information.vue' /* webpackChunkName: "components/ko11-information" */).then(c => wrapFunctional(c.default || c))
export const Ko11ListTrending = () => import('../..\\components\\template11\\Ko11-listTrending.vue' /* webpackChunkName: "components/ko11-list-trending" */).then(c => wrapFunctional(c.default || c))
export const Ko11Parallax = () => import('../..\\components\\template11\\Ko11-parallax.vue' /* webpackChunkName: "components/ko11-parallax" */).then(c => wrapFunctional(c.default || c))
export const Ko11Section = () => import('../..\\components\\template11\\Ko11-section.vue' /* webpackChunkName: "components/ko11-section" */).then(c => wrapFunctional(c.default || c))
export const Ko11TrendingProduct = () => import('../..\\components\\template11\\Ko11-trendingProduct.vue' /* webpackChunkName: "components/ko11-trending-product" */).then(c => wrapFunctional(c.default || c))
export const Ko11TrendingProductHoko = () => import('../..\\components\\template11\\Ko11-trendingProductHoko.vue' /* webpackChunkName: "components/ko11-trending-product-hoko" */).then(c => wrapFunctional(c.default || c))
export const Newsletter = () => import('../..\\components\\template11\\_newsletter\\newsletter.vue' /* webpackChunkName: "components/newsletter" */).then(c => wrapFunctional(c.default || c))
export const CarouselBannerCarousel = () => import('../..\\components\\template11\\_carouselBanner\\banner-carousel.vue' /* webpackChunkName: "components/carousel-banner-carousel" */).then(c => wrapFunctional(c.default || c))
export const Ko12IFooter = () => import('../..\\components\\template12\\Ko12-IFooter.vue' /* webpackChunkName: "components/ko12-i-footer" */).then(c => wrapFunctional(c.default || c))
export const Ko12IHeader = () => import('../..\\components\\template12\\Ko12-IHeader.vue' /* webpackChunkName: "components/ko12-i-header" */).then(c => wrapFunctional(c.default || c))
export const Ko12IHeroImage = () => import('../..\\components\\template12\\Ko12-IHeroImage.vue' /* webpackChunkName: "components/ko12-i-hero-image" */).then(c => wrapFunctional(c.default || c))
export const Ko12IMainSection = () => import('../..\\components\\template12\\Ko12-IMainSection.vue' /* webpackChunkName: "components/ko12-i-main-section" */).then(c => wrapFunctional(c.default || c))
export const ProductCard = () => import('../..\\components\\template12\\ProductCard.vue' /* webpackChunkName: "components/product-card" */).then(c => wrapFunctional(c.default || c))
export const ProductDetail = () => import('../..\\components\\template12\\productDetail.vue' /* webpackChunkName: "components/product-detail" */).then(c => wrapFunctional(c.default || c))
export const SectionWithTitle = () => import('../..\\components\\template12\\SectionWithTitle.vue' /* webpackChunkName: "components/section-with-title" */).then(c => wrapFunctional(c.default || c))
export const MixinsComponentProps = () => import('../..\\components\\template12\\mixins\\ComponentProps.vue' /* webpackChunkName: "components/mixins-component-props" */).then(c => wrapFunctional(c.default || c))
export const ItemsProductSlide = () => import('../..\\components\\template12\\_items\\productSlide.vue' /* webpackChunkName: "components/items-product-slide" */).then(c => wrapFunctional(c.default || c))
export const KoContact1 = () => import('../..\\components\\template13\\Ko-Contact-1.vue' /* webpackChunkName: "components/ko-contact1" */).then(c => wrapFunctional(c.default || c))
export const KoProductFavoritos1 = () => import('../..\\components\\template13\\Ko-ProductFavoritos-1.vue' /* webpackChunkName: "components/ko-product-favoritos1" */).then(c => wrapFunctional(c.default || c))
export const Ko13Banner = () => import('../..\\components\\template13\\Ko13-Banner.vue' /* webpackChunkName: "components/ko13-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko13Information = () => import('../..\\components\\template13\\Ko13-information.vue' /* webpackChunkName: "components/ko13-information" */).then(c => wrapFunctional(c.default || c))
export const Ko13InfoText = () => import('../..\\components\\template13\\Ko13-infoText.vue' /* webpackChunkName: "components/ko13-info-text" */).then(c => wrapFunctional(c.default || c))
export const Ko13Newsletter = () => import('../..\\components\\template13\\Ko13-Newsletter.vue' /* webpackChunkName: "components/ko13-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko13ProductList = () => import('../..\\components\\template13\\Ko13-ProductList.vue' /* webpackChunkName: "components/ko13-product-list" */).then(c => wrapFunctional(c.default || c))
export const BlogKoArticulo = () => import('../..\\components\\template13\\_blog\\Ko-articulo.vue' /* webpackChunkName: "components/blog-ko-articulo" */).then(c => wrapFunctional(c.default || c))
export const BlogKoBlog = () => import('../..\\components\\template13\\_blog\\Ko-Blog.vue' /* webpackChunkName: "components/blog-ko-blog" */).then(c => wrapFunctional(c.default || c))
export const Ko14Banner = () => import('../..\\components\\template14\\ko14-Banner.vue' /* webpackChunkName: "components/ko14-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko14Information = () => import('../..\\components\\template14\\ko14-information.vue' /* webpackChunkName: "components/ko14-information" */).then(c => wrapFunctional(c.default || c))
export const Ko14ListBlogHome = () => import('../..\\components\\template14\\ko14-listBlogHome.vue' /* webpackChunkName: "components/ko14-list-blog-home" */).then(c => wrapFunctional(c.default || c))
export const Ko14Logos = () => import('../..\\components\\template14\\ko14-logos.vue' /* webpackChunkName: "components/ko14-logos" */).then(c => wrapFunctional(c.default || c))
export const Ko14Newsletter = () => import('../..\\components\\template14\\ko14-Newsletter.vue' /* webpackChunkName: "components/ko14-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko14Offers = () => import('../..\\components\\template14\\ko14-offers.vue' /* webpackChunkName: "components/ko14-offers" */).then(c => wrapFunctional(c.default || c))
export const Ko14OffersProduct = () => import('../..\\components\\template14\\ko14-offersProduct.vue' /* webpackChunkName: "components/ko14-offers-product" */).then(c => wrapFunctional(c.default || c))
export const Ko14ProductListHome = () => import('../..\\components\\template14\\ko14-productListHome.vue' /* webpackChunkName: "components/ko14-product-list-home" */).then(c => wrapFunctional(c.default || c))
export const CardBlogCard = () => import('../..\\components\\template14\\_cardBlog\\blogCard.vue' /* webpackChunkName: "components/card-blog-card" */).then(c => wrapFunctional(c.default || c))
export const CardBlogKoArticulo = () => import('../..\\components\\template14\\_cardBlog\\Ko-articulo.vue' /* webpackChunkName: "components/card-blog-ko-articulo" */).then(c => wrapFunctional(c.default || c))
export const CardBlogKoIndex = () => import('../..\\components\\template14\\_cardBlog\\Ko-index.vue' /* webpackChunkName: "components/card-blog-ko-index" */).then(c => wrapFunctional(c.default || c))
export const CardProductCard = () => import('../..\\components\\template14\\_cardProduct\\ProductCard.vue' /* webpackChunkName: "components/card-product-card" */).then(c => wrapFunctional(c.default || c))
export const LateralMenu = () => import('../..\\components\\template14\\_lateral\\_lateralMenu.vue' /* webpackChunkName: "components/lateral-menu" */).then(c => wrapFunctional(c.default || c))
export const Ko15Banner = () => import('../..\\components\\template15\\ko15-Banner.vue' /* webpackChunkName: "components/ko15-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko15Banner2 = () => import('../..\\components\\template15\\ko15-Banner2.vue' /* webpackChunkName: "components/ko15-banner2" */).then(c => wrapFunctional(c.default || c))
export const Ko15Categories = () => import('../..\\components\\template15\\ko15-Categories.vue' /* webpackChunkName: "components/ko15-categories" */).then(c => wrapFunctional(c.default || c))
export const Ko15Contact = () => import('../..\\components\\template15\\Ko15-Contact.vue' /* webpackChunkName: "components/ko15-contact" */).then(c => wrapFunctional(c.default || c))
export const Ko15Content = () => import('../..\\components\\template15\\ko15-Content.vue' /* webpackChunkName: "components/ko15-content" */).then(c => wrapFunctional(c.default || c))
export const Ko15Information = () => import('../..\\components\\template15\\ko15-information.vue' /* webpackChunkName: "components/ko15-information" */).then(c => wrapFunctional(c.default || c))
export const Ko15Information2 = () => import('../..\\components\\template15\\ko15-information2.vue' /* webpackChunkName: "components/ko15-information2" */).then(c => wrapFunctional(c.default || c))
export const Ko15InformationLogos = () => import('../..\\components\\template15\\ko15-informationLogos.vue' /* webpackChunkName: "components/ko15-information-logos" */).then(c => wrapFunctional(c.default || c))
export const Ko15ListProductsOffers = () => import('../..\\components\\template15\\ko15-listProductsOffers.vue' /* webpackChunkName: "components/ko15-list-products-offers" */).then(c => wrapFunctional(c.default || c))
export const Ko15Logos = () => import('../..\\components\\template15\\ko15-logos.vue' /* webpackChunkName: "components/ko15-logos" */).then(c => wrapFunctional(c.default || c))
export const Ko15Newsletter = () => import('../..\\components\\template15\\Ko15-Newsletter.vue' /* webpackChunkName: "components/ko15-newsletter" */).then(c => wrapFunctional(c.default || c))
export const Ko15ProductListFilter = () => import('../..\\components\\template15\\Ko15-ProductListFilter.vue' /* webpackChunkName: "components/ko15-product-list-filter" */).then(c => wrapFunctional(c.default || c))
export const Ko15ProductListHome = () => import('../..\\components\\template15\\ko15-productListHome.vue' /* webpackChunkName: "components/ko15-product-list-home" */).then(c => wrapFunctional(c.default || c))
export const Ko16Banner = () => import('../..\\components\\template16\\ko16-Banner.vue' /* webpackChunkName: "components/ko16-banner" */).then(c => wrapFunctional(c.default || c))
export const Ko16Categories = () => import('../..\\components\\template16\\ko16-Categories.vue' /* webpackChunkName: "components/ko16-categories" */).then(c => wrapFunctional(c.default || c))
export const Ko16Contact = () => import('../..\\components\\template16\\Ko16-Contact.vue' /* webpackChunkName: "components/ko16-contact" */).then(c => wrapFunctional(c.default || c))
export const Ko16Content = () => import('../..\\components\\template16\\ko16-Content.vue' /* webpackChunkName: "components/ko16-content" */).then(c => wrapFunctional(c.default || c))
export const Ko16Information = () => import('../..\\components\\template16\\ko16-Information.vue' /* webpackChunkName: "components/ko16-information" */).then(c => wrapFunctional(c.default || c))
export const Ko16InformationStore = () => import('../..\\components\\template16\\ko16-informationStore.vue' /* webpackChunkName: "components/ko16-information-store" */).then(c => wrapFunctional(c.default || c))
export const Ko16ListBlogHome = () => import('../..\\components\\template16\\ko16-listBlogHome.vue' /* webpackChunkName: "components/ko16-list-blog-home" */).then(c => wrapFunctional(c.default || c))
export const Ko16Logos = () => import('../..\\components\\template16\\ko16-logos.vue' /* webpackChunkName: "components/ko16-logos" */).then(c => wrapFunctional(c.default || c))
export const Ko16Offers = () => import('../..\\components\\template16\\ko16-Offers.vue' /* webpackChunkName: "components/ko16-offers" */).then(c => wrapFunctional(c.default || c))
export const Ko16ProductListHome = () => import('../..\\components\\template16\\ko16-productListHome.vue' /* webpackChunkName: "components/ko16-product-list-home" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
