stages:
  # - test
  # - code-coverage
  # - build
  - prepare-files

image: node

before_script:
  - apk add openssh-client util-linux --update curl && rm -rf /var/cache/apk/*
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - free -m | grep -v "Swap" # RAM
  - df -h| grep -E "Filesystem|overlay" # storage
  - lscpu | grep -E "^CPU\(s\)" # CPUs
  - whoami

cache:
  paths:
    - "node_modules/"
    - "$HOME/.npm/"

# test:
#   stage: test
#   tags:
#     - processtempo
#   script:
#     - npm install
#     - npm run test

# code-coverage:
#   stage: code-coverage
#   tags:
#     - processtempo
#   script:
#     - npm run test:cov

# build:
#   stage: build
#   tags:
#     - processtempo
#   script:
#     - npm run build
#     - ls -l
#     - cp Dockerfile dist/
#     - cp package.json dist/
#     - ls -l dist/
#   artifacts:
#     paths:
#       - ./dist

prepare-files:
  stage: prepare-files
  script:
    # - scp -o StrictHostKeyChecking=no ./buildRAD.tgz root@67.227.206.29:.
    - ssh -o StrictHostKeyChecking=no ubuntu@18.190.124.250 "ls -l"
    # - ssh -o StrictHostKeyChecking=no root@67.227.206.29 "rm -rf build && tar xzf buildRAD.tgz && cd ./dist && ls -l"
    # - ssh -o StrictHostKeyChecking=no root@67.227.206.29 "cd ./dist; docker build -t processtempo:${VERSION_PT4_MS_WORKSPACES_DEV} ."
    # - ssh -o StrictHostKeyChecking=no root@67.227.206.29 "sudo docker login -u="processtempo+pablo" -p="H1YWUZUEUG6DA8PHR9O8RBFDURM80KN5C7K1HD0WC2J7OV1W8480PSVSF0YWNXRJ" registry.ford.com;
    #   docker tag  processtempo:${VERSION_PT4_MS_WORKSPACES_DEV} registry.ford.com/processtempo/pt4-ms-workspaces:${VERSION_PT4_MS_WORKSPACES_DEV};
    #   docker push registry.ford.com/processtempo/pt4-ms-workspaces:${VERSION_PT4_MS_WORKSPACES_DEV}"

      