stages:
  - install-dependecies
  - compile-files
  - deploy-production
  - deploy-develop
image: node
before_script:
  - apk add openssh-client util-linux --update curl && rm -rf /var/cache/apk/*
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - free -m | grep -v "Swap" # RAM
  - df -h| grep -E "Filesystem|overlay" # storage
  - lscpu | grep -E "^CPU\(s\)" # CPUs
install-dependecies:
  stage: install-dependecies
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@18.190.124.250 "cd template-nuxt-dokku && sudo git pull --no-edit && npm install"
  only: 
    - master

compile-files:
  stage: compile-files
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@18.190.124.250 "sudo su && source ~/.nvm/nvm.sh && cd template-nuxt-dokku && node --version && nvm list  && nvm use 14  && npm run build -y"
  only: 
    - master

deploy-production:
  stage: deploy-production
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@18.190.124.250 "cd template-nuxt-dokku && sudo pm2 delete appnuxt && sudo pm2 start npm --name "appnuxt" -- start && sudo pm2 save"
  only: 
    - master

deploy-develop:
  stage: deploy-develop
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@13.59.90.192 "source ~/.nvm/nvm.sh && ./up.sh"
  only: 
    - develop
      