image: node:6.10-alpine

before_script:
  - npm install

stages:
  - pages

pages:
  stage: pages
  cache:
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master
  # - git-push dokku@159.65.241.57:template-nuxt-app
