stages:
  - deploy-production
  - deploy-develop
image: node
before_script:
  - apk add openssh-client util-linux --update curl && rm -rf /var/cache/apk/*
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - free -m | grep -v "Swap" # RAM
  - df -h| grep -E "Filesystem|overlay" # storage
  - lscpu | grep -E "^CPU\(s\)" # CPUs
deploy-production:
  stage: deploy-production
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@18.190.124.250 "sudo ./up.sh"
  only: 
    - master
deploy-develop:
  stage: deploy-develop
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@13.59.90.192 "source ~/.nvm/nvm.sh && ls -l && node --version"
  only: 
    - develop
      