before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'dokku.example.com' >> ~/.ssh/known_hosts
stages:
  - deploy

deploy_to_dokku:
stage: deploy
script:
  - git checkout master
  - git pull
  - git-push dokku@159.65.241.57:template-nuxt-app
