services:
  stores-templates-nuxt-app:
    image: ghcr.io/komercia2/stores-templates-nuxt:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: unless-stopped
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.4'
          memory: 512M
    networks:
      - komercia-network

networks:
  komercia-network:
    external: true
